# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ben Swift"
description: > # this means to ignore newlines until "email:"
  develop, design, inspire

email: ben@swift404.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/golden-gate.jpg"

name: 'Ben Swift'
author: 'Ben Swift'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://swift404.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@swifty404'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/swifty404
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/benswift404
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
